from io import BytesIO

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from PIL import Image, UnidentifiedImageError

from animalness_gate.service import get_animalness_gate_service
from app.services.body_area_router import route_body_area
from app.services.cat_eye import CatEyeInvalidCropError, get_cat_eye_model
from app.services.dog_eye import get_dog_eye_model
from app.services.recommendation import build_recommendation
from app.services.skin import get_skin_model
from app.services.species_router import route_species


router = APIRouter(
    prefix="/api",
    tags=["prediction"],
)


def _parse_bool_field(value, field_name: str, allow_none: bool = False) -> bool | None:
    if value is None:
        if allow_none:
            return None
        return False
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in ("true", "1", "yes"):
            return True
        if normalized in ("false", "0", "no"):
            return False
        if allow_none and normalized in ("", "none", "null"):
            return None
    raise HTTPException(
        status_code=400,
        detail=f"Invalid value for {field_name}: must be a boolean.",
    )


@router.post("/predict")
async def predict(
    image: UploadFile = File(...),
    species: str = Form(...),
    body_area: str = Form(...),
    severity: str | None = Form(None),
    active_hemorrhage: bool | str = Form(False),
    low_risk_evidence: bool | str | None = Form(None),
    observed_condition: str | None = Form(None),
    conflicts: str | None = Form(None),
):
    """
    Route an uploaded animal image to the appropriate model.

    Current implementation:
    - Flow:
      1. Image validation
      2. Selected species validation
      3. Animalness Gate validation (REJECT / UNCERTAIN returns gate response immediately)
      4. Body-area validation
      5. Disease model inference (Dog Eye / Skin)
      6. Recommendation schema generation
    - Species and body area are explicitly supplied by the client.
    - Dog + eye routes to the frozen dog-eye-v1 model.
    - Cat + eye routes to the frozen scanai_cat_eye_efficientnet_b0_v1 model.
    - Skin routes to the finalized SCANAI-SKIN-PHASE4B model.
    - Model output is transformed into the approved v1
      recommendation schema.
    - Other model routes are not implemented yet.

    Important boundaries:
    - Never silently reroute species.
    - Skin model output is screening-only.
    - Skin confidence/condition is not converted into severity or urgency.
    - No clinical treatment recommendation is generated by the
      Skin model route.
    """

    if hasattr(severity, "default"):
        severity = severity.default
    if hasattr(active_hemorrhage, "default"):
        active_hemorrhage = active_hemorrhage.default or False
    if hasattr(low_risk_evidence, "default"):
        low_risk_evidence = low_risk_evidence.default
    if hasattr(observed_condition, "default"):
        observed_condition = observed_condition.default
    if hasattr(conflicts, "default"):
        conflicts = conflicts.default

    active_hemorrhage = _parse_bool_field(active_hemorrhage, "active_hemorrhage", allow_none=False)
    low_risk_evidence = _parse_bool_field(low_risk_evidence, "low_risk_evidence", allow_none=True)

    if severity is not None:
        if isinstance(severity, str):
            norm_severity = severity.strip().lower()
            if norm_severity in ("", "none", "null"):
                severity = None
            elif norm_severity in ("mild", "moderate", "severe"):
                severity = norm_severity
            else:
                raise HTTPException(
                    status_code=400,
                    detail="Invalid value for severity: must be one of 'mild', 'moderate', 'severe'.",
                )
        else:
            raise HTTPException(
                status_code=400,
                detail="Invalid value for severity: must be one of 'mild', 'moderate', 'severe'.",
            )

    # --------------------------------------------------------
    # Image validation
    # --------------------------------------------------------

    if (
        not image.content_type
        or not image.content_type.startswith("image/")
    ):
        raise HTTPException(
            status_code=400,
            detail="Uploaded file must be an image.",
        )

    try:
        contents = await image.read()
        pil_image = Image.open(BytesIO(contents))
        pil_image.load()

    except (UnidentifiedImageError, OSError):
        raise HTTPException(
            status_code=400,
            detail="Unable to read the uploaded image.",
        )

    # --------------------------------------------------------
    # Selected species validation
    # --------------------------------------------------------

    try:
        routed_species = route_species(species)
    except ValueError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    # --------------------------------------------------------
    # Animalness Gate validation
    # --------------------------------------------------------

    gate_service = get_animalness_gate_service()
    gate_result = gate_service.validate(pil_image, selected_species=routed_species)

    if gate_result.get("decision") in ("REJECT", "UNCERTAIN"):
        return gate_result

    # --------------------------------------------------------
    # Body-area routing / validation
    # --------------------------------------------------------

    try:
        routed_body_area = route_body_area(body_area)
    except ValueError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    parsed_conflicts = None
    if conflicts:
        if isinstance(conflicts, str):
            try:
                import json
                parsed = json.loads(conflicts)
                if isinstance(parsed, list):
                    parsed_conflicts = parsed
                else:
                    parsed_conflicts = [conflicts]
            except Exception:
                parsed_conflicts = [c.strip() for c in conflicts.split(",") if c.strip()]
        elif isinstance(conflicts, list):
            parsed_conflicts = conflicts

    # --------------------------------------------------------
    # Dog + Eye model routing
    # --------------------------------------------------------

    if (
        routed_species == "dog"
        and routed_body_area == "eye"
    ):
        try:
            model = get_dog_eye_model()
            result = model.predict(pil_image)

        except Exception as exc:
            raise HTTPException(
                status_code=500,
                detail=f"Dog eye inference failed: {exc}",
            ) from exc

        return build_recommendation(
            routed_species,
            routed_body_area,
            result,
            severity=severity,
            active_hemorrhage=active_hemorrhage,
            low_risk_evidence=low_risk_evidence,
            observed_condition=observed_condition,
            conflicts=parsed_conflicts,
        )

    # --------------------------------------------------------
    # Cat + Eye model routing
    # --------------------------------------------------------

    if (
        routed_species == "cat"
        and routed_body_area == "eye"
    ):
        try:
            model = get_cat_eye_model()
            result = model.predict(pil_image)

        except (ValueError, CatEyeInvalidCropError) as exc:
            raise HTTPException(
                status_code=400,
                detail=str(exc),
            ) from exc

        except Exception as exc:
            raise HTTPException(
                status_code=500,
                detail=f"Cat eye inference failed: {exc}",
            ) from exc

        return build_recommendation(
            routed_species,
            routed_body_area,
            result,
            severity=severity,
            active_hemorrhage=active_hemorrhage,
            low_risk_evidence=low_risk_evidence,
            observed_condition=observed_condition,
            conflicts=parsed_conflicts,
        )

    # --------------------------------------------------------
    # Skin model routing
    #
    # The finalized Skin model is shared by supported species.
    # Do not derive severity or urgency from Skin output.
    # --------------------------------------------------------

    if routed_body_area == "skin":
        try:
            model = get_skin_model()
            result = model.predict(pil_image)

        except Exception as exc:
            raise HTTPException(
                status_code=500,
                detail=f"Skin inference failed: {exc}",
            ) from exc

        return build_recommendation(
            routed_species,
            routed_body_area,
            result,
            severity=severity,
            active_hemorrhage=active_hemorrhage,
            low_risk_evidence=low_risk_evidence,
            observed_condition=observed_condition,
            conflicts=parsed_conflicts,
        )

    # --------------------------------------------------------
    # Models not implemented yet
    # --------------------------------------------------------

    raise HTTPException(
        status_code=501,
        detail=(
            f"No model route is currently implemented for "
            f"species='{routed_species}', "
            f"body_area='{routed_body_area}'."
        ),
    )